name: Secure Cloud Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::767397816705:role/GitHubActionsWorkflowRole
          aws-region: us-east-1

      - name: Deploy to S3 Bucket
        run: |
          aws s3 sync . s3://olayinka-portfolio-2026 --exclude ".git*" --exclude ".github*"

          